---
abstract: 'Peek into the internal number representation'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MyPeek
provides:
  Acme::MyPeek:
    file: lib/Acme/MyPeek.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
